partyA=set(['Park','Kim','Lee'])
partyB=set(['Park','길동','몽룡'])
print("파티에 참석한 모든 사람")
print(partyA|partyB)
print("------------------------------------")
print("2개의 파티에 모두 참석한 사람")
print(partyA&partyB)
print("------------------------------------")
print(partyA-partyB)
print("------------------------------------")
print(partyB-partyA)