diposit=int(input("예금액 입력 : "))
rate=eval(input("이자율 입력(%) : "))
interest=(diposit*(rate/100))
total=(diposit+interest)

print("-------------------------")
print("예금액 : %d 원"%diposit)
print("이자율  : %.1f %%"%rate)
print("예금이자 : %d 원"%interest)
print("잔액 : %d 원"%total)
print("-------------------------")
print("예금액 : "+format(diposit,',')+" 원")
print("이자율 : %.1f %%"%rate)
print("예금이자 : "+format(int(interest),',',)+" 원")
print("잔액 : "+format(int(total),',')+" 원")
