# Generated by Django 4.1 on 2022-08-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesRes', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant',
            new_name='restaurant_name',
        ),
    ]
